let qr; // Declare a global variable to store the QR code instance
let canvas; // Declare a global variable to store the canvas element

function generateQRCode() {
    const inputText = document.getElementById('inputText').value;
    const color = document.getElementById('colorPicker').value;

    // If a QR code instance exists, remove it
    if (qr) {
        qr.clear(); // Clear the existing QR code
    }

    // Clear the entire content of the qrcode div
    document.getElementById('qrcode').innerHTML = '';

    // Create a new QR code instance using qrcode.js
    qr = new QRCode(document.getElementById("qrcode"), {
        text: inputText,
        width: 128,
        height: 128,
        colorDark: color, // Set the color of the dark modules (foreground)
    });

    // Get the canvas element generated by qrcode.js
    canvas = document.getElementById('qrcode').querySelector('canvas');

    // Show the download buttons after generating the QR code
    document.getElementById('downloadImageBtn').style.display = 'inline-block';
    document.getElementById('downloadPDFBtn').style.display = 'inline-block';
}

function downloadQRCodeAsImage() {
    if (canvas) {
        const url = canvas.toDataURL('image/png');
        const link = document.createElement('a');
        link.href = url;
        link.download = 'qrcode.png';
        link.click();
    }
}

function downloadQRCodeAsPDF() {
    if (canvas) {
        const pdf = new jsPDF();

        const imgData = canvas.toDataURL('image/png');
        pdf.addImage(imgData, 'PNG', 10, 10, 100, 100);
        pdf.save('qrcode.pdf');
    }
}
